# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-13 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_organizers',
            field=models.TextField(default='unknown'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_rooms',
            field=models.CharField(choices=[('1', 'lecture 1'), ('2', 'lecture2'), ('3', 'lecture3')], default=1, max_length=500),
            preserve_default=False,
        ),
    ]
