# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-16 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_auto_20190213_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_rooms',
        ),
    ]
