# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-16 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_remove_event_event_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_rooms',
            field=models.CharField(choices=[('1', 'lecture 1'), ('2', 'lecture2'), ('3', 'lecture3')], default=0, max_length=500),
            preserve_default=False,
        ),
    ]
