# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-02-16 08:20
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0005_event_event_rooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_rooms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'lecture 1'), ('2', 'lecture2'), ('3', 'lecture3')], max_length=5),
        ),
    ]
