# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-08 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0007_auto_20190307_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_rooms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'lecture 1'), (2, 'lecture2'), (3, 'lecture3')], max_length=5),
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('event_date', 'start_time')]),
        ),
    ]
