# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-09 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0008_auto_20190308_0835'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([]),
        ),
    ]
